# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/clinica_upn_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# ¡ATENCIÓN! Cambia "root" por la contraseña de tu MySQL:
spring.datasource.password=admin123

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Usamos 'none' o 'update' para que Spring NO borre tu BD creada con tus scripts SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080